Repository fridge-manager-project/backend, pull requests merged in 2024-03, with the labels that each got.

#83 현재까지 푸쉬알림 진행
  build.gradle
  src/main/java/com/challenger/fridge/controller/NoticeController.java
  src/main/java/com/challenger/fridge/domain/Member.java
  src/main/java/com/challenger/fridge/domain/Notice.java
  src/main/java/com/challenger/fridge/dto/notice/DeviceTokenRequest.java
  src/main/java/com/challenger/fridge/dto/notice/FcmMessage.java
  src/main/java/com/challenger/fridge/repository/MemberRepository.java
  src/main/java/com/challenger/fridge/repository/NoticeRepository.java
  src/main/java/com/challenger/fridge/service/FirebaseCloudMessageService.java
  src/main/java/com/challenger/fridge/service/NoticeService.java
  src/main/resources/firebase/firebase_service_key.json
Labels: enhancement

#84 상품 카테고리 재설정 및 데이터 삽입
  src/main/java/com/challenger/fridge/domain/StorageItem.java
  src/main/java/com/challenger/fridge/dto/box/request/StorageBoxSaveRequest.java
  src/main/java/com/challenger/fridge/dto/item/request/StorageItemRequest.java
  src/main/java/com/challenger/fridge/dto/item/request/StorageItemUpdateRequest.java
  src/main/java/com/challenger/fridge/dto/item/response/StorageItemResponse.java
  src/main/java/com/challenger/fridge/service/StorageService.java
Labels: enhancement

#85 상품 카테고리 재설정
  src/main/java/com/challenger/fridge/domain/Category.java
  src/main/java/com/challenger/fridge/util/DataLoadService.java
  src/main/java/com/challenger/fridge/util/ItemAndCategoryLoad.java
  src/main/resources/static/itemData.csv
  src/test/java/com/challenger/fridge/repository/CartRepositoryTest.java
Labels: enhancement

#88 Feature - 상품 정보 조회 api
  build.gradle
  src/main/java/com/challenger/fridge/config/CacheConfig.java
  src/main/java/com/challenger/fridge/controller/ItemController.java
  src/main/java/com/challenger/fridge/domain/Member.java
  src/main/java/com/challenger/fridge/dto/item/response/ItemInfoResponse.java
  src/main/java/com/challenger/fridge/repository/ItemRepository.java
  src/main/java/com/challenger/fridge/service/ItemService.java
  src/main/resources/static/itemData.csv
Labels: bug, enhancement

#89 상품 정보 조회 api 및 회원 생성 메서드 수정
  build.gradle
  src/main/java/com/challenger/fridge/config/CacheConfig.java
  src/main/java/com/challenger/fridge/controller/ItemController.java
  src/main/java/com/challenger/fridge/controller/NoticeController.java
  src/main/java/com/challenger/fridge/domain/Category.java
  src/main/java/com/challenger/fridge/domain/Member.java
  src/main/java/com/challenger/fridge/domain/Notice.java
  src/main/java/com/challenger/fridge/dto/item/response/ItemInfoResponse.java
  src/main/java/com/challenger/fridge/dto/notice/DeviceTokenRequest.java
  src/main/java/com/challenger/fridge/dto/notice/FcmMessage.java
  src/main/java/com/challenger/fridge/repository/ItemRepository.java
  src/main/java/com/challenger/fridge/repository/MemberRepository.java
  src/main/java/com/challenger/fridge/repository/NoticeRepository.java
  src/main/java/com/challenger/fridge/service/FirebaseCloudMessageService.java
  src/main/java/com/challenger/fridge/service/ItemService.java
  src/main/java/com/challenger/fridge/service/NoticeService.java
  src/main/java/com/challenger/fridge/util/DataLoadService.java
  src/main/java/com/challenger/fridge/util/ItemAndCategoryLoad.java
  src/main/resources/firebase/firebase_service_key.json
  src/main/resources/static/itemData.csv
  src/test/java/com/challenger/fridge/repository/CartRepositoryTest.java
Labels: bug, enhancement

#90 장바구니 상품 조회 API 수정 및 상품 수량 조절 API 구현
  src/main/java/com/challenger/fridge/controller/CartController.java
  src/main/java/com/challenger/fridge/domain/CartItem.java
  src/main/java/com/challenger/fridge/dto/cart/CartItemRequest.java
  src/main/java/com/challenger/fridge/dto/cart/CartItemResponse.java
  src/main/java/com/challenger/fridge/dto/cart/CartResponse.java
  src/main/java/com/challenger/fridge/dto/cart/ItemCountRequest.java
  src/main/java/com/challenger/fridge/service/CartService.java
  src/main/java/com/challenger/fridge/service/CartStorageService.java
  src/test/java/com/challenger/fridge/service/CartServiceTest.java
  src/test/java/com/challenger/fridge/service/CartStorageServiceTest.java
Labels: enhancement

#91 Feature: 장바구니 상품 조회 API 수정 및 상품 수량 조절 API 구현
  src/main/java/com/challenger/fridge/controller/CartController.java
  src/main/java/com/challenger/fridge/domain/CartItem.java
  src/main/java/com/challenger/fridge/dto/cart/CartItemRequest.java
  src/main/java/com/challenger/fridge/dto/cart/CartItemResponse.java
  src/main/java/com/challenger/fridge/dto/cart/CartResponse.java
  src/main/java/com/challenger/fridge/dto/cart/ItemCountRequest.java
  src/main/java/com/challenger/fridge/service/CartService.java
  src/main/java/com/challenger/fridge/service/CartStorageService.java
  src/test/java/com/challenger/fridge/service/CartServiceTest.java
  src/test/java/com/challenger/fridge/service/CartStorageServiceTest.java
Labels: enhancement

#93 Feature: 회원 비밀번호, 닉네임 수정 API
  src/main/java/com/challenger/fridge/controller/CartController.java
  src/main/java/com/challenger/fridge/controller/MemberController.java
  src/main/java/com/challenger/fridge/controller/SignController.java
  src/main/java/com/challenger/fridge/domain/Member.java
  src/main/java/com/challenger/fridge/dto/cart/CartItemRequest.java
  src/main/java/com/challenger/fridge/dto/cart/ItemCountRequest.java
  src/main/java/com/challenger/fridge/dto/member/ChangePasswordRequest.java
  src/main/java/com/challenger/fridge/dto/member/MemberInfoRequest.java
  src/main/java/com/challenger/fridge/dto/member/MemberInfoResponse.java
  src/main/java/com/challenger/fridge/dto/member/MemberNicknameRequest.java
  src/main/java/com/challenger/fridge/dto/sign/SignInRequest.java
  src/main/java/com/challenger/fridge/dto/sign/SignUpRequest.java
  src/main/java/com/challenger/fridge/service/MemberService.java
  src/main/java/com/challenger/fridge/service/SignService.java
  src/test/java/com/challenger/fridge/controller/SignControllerTest.java
  src/test/java/com/challenger/fridge/repository/CartRepositoryTest.java
  src/test/java/com/challenger/fridge/repository/StorageRepositoryTest.java
  src/test/java/com/challenger/fridge/service/MemberServiceTest.java
  src/test/java/com/challenger/fridge/service/SignServiceTest.java
  src/test/java/com/challenger/fridge/service/SignServiceUnitTest.java
  src/test/java/com/challenger/fridge/service/StorageServiceTest.java
Labels: enhancement

#94 Feature: 회원 비밀번호, 닉네임 수정 API 및 Validation 적용
  src/main/java/com/challenger/fridge/controller/CartController.java
  src/main/java/com/challenger/fridge/controller/MemberController.java
  src/main/java/com/challenger/fridge/controller/SignController.java
  src/main/java/com/challenger/fridge/domain/Member.java
  src/main/java/com/challenger/fridge/dto/cart/CartItemRequest.java
  src/main/java/com/challenger/fridge/dto/cart/ItemCountRequest.java
  src/main/java/com/challenger/fridge/dto/member/ChangePasswordRequest.java
  src/main/java/com/challenger/fridge/dto/member/MemberInfoRequest.java
  src/main/java/com/challenger/fridge/dto/member/MemberInfoResponse.java
  src/main/java/com/challenger/fridge/dto/member/MemberNicknameRequest.java
  src/main/java/com/challenger/fridge/dto/sign/SignInRequest.java
  src/main/java/com/challenger/fridge/dto/sign/SignUpRequest.java
  src/main/java/com/challenger/fridge/service/MemberService.java
  src/main/java/com/challenger/fridge/service/SignService.java
  src/test/java/com/challenger/fridge/controller/SignControllerTest.java
  src/test/java/com/challenger/fridge/repository/CartRepositoryTest.java
  src/test/java/com/challenger/fridge/repository/StorageRepositoryTest.java
  src/test/java/com/challenger/fridge/service/MemberServiceTest.java
  src/test/java/com/challenger/fridge/service/SignServiceTest.java
  src/test/java/com/challenger/fridge/service/SignServiceUnitTest.java
  src/test/java/com/challenger/fridge/service/StorageServiceTest.java
Labels: enhancement

#95 Refactor: 장바구니 상품 수량 조절 API 수정
  src/main/java/com/challenger/fridge/dto/cart/ItemCountRequest.java
Labels: bug

#96 Refactor: ItemCountRequest 기본 생성자 추가
  src/main/java/com/challenger/fridge/dto/cart/ItemCountRequest.java
Labels: bug

#97 Refactor : MemberNicknameReuqest 기본 생성자 추가 및 닉네임 validation 수정
  src/main/java/com/challenger/fridge/dto/member/MemberNicknameRequest.java
  src/main/java/com/challenger/fridge/dto/sign/SignUpRequest.java
  src/test/java/com/challenger/fridge/repository/CartRepositoryTest.java
Labels: bug

#99 Chore: 상품 고유 정보 수정 및 AccessToken 유효시간 재설정
  src/main/resources/application.yml
  src/main/resources/static/itemData.csv
Labels: bug

#100 Feature: 장바구니 상품 구매 check API 구현 및 테스트 작성
  src/main/java/com/challenger/fridge/controller/CartController.java
  src/main/java/com/challenger/fridge/domain/CartItem.java
  src/main/java/com/challenger/fridge/service/CartService.java
  src/test/java/com/challenger/fridge/repository/CartRepositoryTest.java
  src/test/java/com/challenger/fridge/service/CartServiceTest.java
Labels: enhancement

#101 Feature: 장바구니 상품 구매 체크 API 구현 및 테스트 작성
  src/main/java/com/challenger/fridge/controller/CartController.java
  src/main/java/com/challenger/fridge/domain/CartItem.java
  src/main/java/com/challenger/fridge/service/CartService.java
  src/test/java/com/challenger/fridge/repository/CartRepositoryTest.java
  src/test/java/com/challenger/fridge/service/CartServiceTest.java
Labels: enhancement

#102 Feature : 장바구니 상품 보관소 이동, 조회 API 수정 및 테스트 수정
  src/main/java/com/challenger/fridge/controller/CartController.java
  src/main/java/com/challenger/fridge/dto/cart/CartItemMoveRequest.java
  src/main/java/com/challenger/fridge/dto/cart/CartItemResponse.java
  src/main/java/com/challenger/fridge/dto/member/MemberNicknameRequest.java
  src/main/java/com/challenger/fridge/dto/sign/SignUpRequest.java
  src/main/java/com/challenger/fridge/repository/CartItemRepository.java
  src/main/java/com/challenger/fridge/service/CartStorageService.java
  src/test/java/com/challenger/fridge/controller/SignControllerTest.java
  src/test/java/com/challenger/fridge/service/CartServiceTest.java
  src/test/java/com/challenger/fridge/service/CartStorageServiceTest.java
Labels: enhancement

#103 Feature: 장바구니 상품 이동, 조회 API 수정 및 테스트 수정
  src/main/java/com/challenger/fridge/controller/CartController.java
  src/main/java/com/challenger/fridge/dto/cart/CartItemMoveRequest.java
  src/main/java/com/challenger/fridge/dto/cart/CartItemResponse.java
  src/main/java/com/challenger/fridge/dto/member/MemberNicknameRequest.java
  src/main/java/com/challenger/fridge/dto/sign/SignUpRequest.java
  src/main/java/com/challenger/fridge/repository/CartItemRepository.java
  src/main/java/com/challenger/fridge/service/CartStorageService.java
  src/test/java/com/challenger/fridge/controller/SignControllerTest.java
  src/test/java/com/challenger/fridge/service/CartServiceTest.java
  src/test/java/com/challenger/fridge/service/CartStorageServiceTest.java
Labels: enhancement

#104 Chore: ec2 인스턴스 무작위 접속 방지를 위한 SecurityConfig 재설정
  src/main/java/com/challenger/fridge/security/SecurityConfig.java
Labels: bug, enhancement

#105 Chore: SecurityConfig url과 Http Method 설정 추가 및 정적자원 설정 해제
  src/main/java/com/challenger/fridge/security/SecurityConfig.java
Labels: bug

#106 Chore: SecurityConfig /sign-up 모든 HttpMethod에 대해 허용
  src/main/java/com/challenger/fridge/security/SecurityConfig.java
Labels: bug

#108 Feature: 푸시알림 전송 후 저장 API 및 조회 API 구현
  .gitignore
  build.gradle
  src/main/java/com/challenger/fridge/FridgeApplication.java
  src/main/java/com/challenger/fridge/config/FirebaseConfig.java
  src/main/java/com/challenger/fridge/config/RedisService.java
  src/main/java/com/challenger/fridge/controller/FCMController.java
  src/main/java/com/challenger/fridge/controller/NoticeController.java
  src/main/java/com/challenger/fridge/controller/NotificationController.java
  src/main/java/com/challenger/fridge/controller/SignController.java
  src/main/java/com/challenger/fridge/domain/Member.java
  src/main/java/com/challenger/fridge/domain/Notice.java
  src/main/java/com/challenger/fridge/domain/notification/Notice.java
  src/main/java/com/challenger/fridge/domain/notification/Notification.java
  src/main/java/com/challenger/fridge/domain/notification/StorageNotification.java
  src/main/java/com/challenger/fridge/dto/item/request/StorageItemRequest.java
  src/main/java/com/challenger/fridge/dto/notice/DeviceTokenRequest.java
  src/main/java/com/challenger/fridge/dto/notice/FcmMessage.java
  src/main/java/com/challenger/fridge/dto/notification/NoticeResponse.java
  src/main/java/com/challenger/fridge/dto/notification/NotificationRequest.java
  src/main/java/com/challenger/fridge/dto/notification/NotificationResponse.java
  src/main/java/com/challenger/fridge/dto/notification/StorageNotificationResponse.java
  src/main/java/com/challenger/fridge/handler/ExceptionResponseHandler.java
  src/main/java/com/challenger/fridge/repository/CartRepository.java
  src/main/java/com/challenger/fridge/repository/FCMTokenRepository.java
  src/main/java/com/challenger/fridge/repository/MemberRepository.java
  src/main/java/com/challenger/fridge/repository/NoticeRepository.java
  src/main/java/com/challenger/fridge/repository/NotificationRepository.java
  src/main/java/com/challenger/fridge/repository/StorageItemRepository.java
  src/main/java/com/challenger/fridge/security/SecurityConfig.java
  src/main/java/com/challenger/fridge/service/FCMService.java
  src/main/java/com/challenger/fridge/service/FirebaseCloudMessageService.java
  src/main/java/com/challenger/fridge/service/NoticeService.java
  src/main/java/com/challenger/fridge/service/NotificationService.java
  src/main/java/com/challenger/fridge/service/SignService.java
  src/main/resources/application.yml
  src/test/java/com/challenger/fridge/service/NotificationServiceTest.java
  src/test/java/com/challenger/fridge/service/SignServiceTest.java
Labels: enhancement

#109 Feature: 푸시알림 전송 및 저장, 알림 조회 API 구현
  .gitignore
  build.gradle
  src/main/java/com/challenger/fridge/FridgeApplication.java
  src/main/java/com/challenger/fridge/config/FirebaseConfig.java
  src/main/java/com/challenger/fridge/config/RedisService.java
  src/main/java/com/challenger/fridge/controller/FCMController.java
  src/main/java/com/challenger/fridge/controller/NoticeController.java
  src/main/java/com/challenger/fridge/controller/NotificationController.java
  src/main/java/com/challenger/fridge/controller/SignController.java
  src/main/java/com/challenger/fridge/controller/StorageBoxController.java
  src/main/java/com/challenger/fridge/controller/StorageController.java
  src/main/java/com/challenger/fridge/domain/Member.java
  src/main/java/com/challenger/fridge/domain/Notice.java
  src/main/java/com/challenger/fridge/domain/box/Freeze.java
  src/main/java/com/challenger/fridge/domain/box/Fridge.java
  src/main/java/com/challenger/fridge/domain/box/StorageBox.java
  src/main/java/com/challenger/fridge/domain/notification/Notice.java
  src/main/java/com/challenger/fridge/domain/notification/Notification.java
  src/main/java/com/challenger/fridge/domain/notification/StorageNotification.java
  src/main/java/com/challenger/fridge/dto/item/request/StorageItemRequest.java
  src/main/java/com/challenger/fridge/dto/notice/DeviceTokenRequest.java
  src/main/java/com/challenger/fridge/dto/notice/FcmMessage.java
  src/main/java/com/challenger/fridge/dto/notification/NoticeResponse.java
  src/main/java/com/challenger/fridge/dto/notification/NotificationRequest.java
  src/main/java/com/challenger/fridge/dto/notification/NotificationResponse.java
  src/main/java/com/challenger/fridge/dto/notification/StorageNotificationResponse.java
  src/main/java/com/challenger/fridge/handler/ExceptionResponseHandler.java
  src/main/java/com/challenger/fridge/repository/CartRepository.java
  src/main/java/com/challenger/fridge/repository/FCMTokenRepository.java
  src/main/java/com/challenger/fridge/repository/MemberRepository.java
  src/main/java/com/challenger/fridge/repository/NoticeRepository.java
  src/main/java/com/challenger/fridge/repository/NotificationRepository.java
  src/main/java/com/challenger/fridge/repository/StorageItemRepository.java
  src/main/java/com/challenger/fridge/security/SecurityConfig.java
  src/main/java/com/challenger/fridge/service/FCMService.java
  src/main/java/com/challenger/fridge/service/FirebaseCloudMessageService.java
  src/main/java/com/challenger/fridge/service/NoticeService.java
  src/main/java/com/challenger/fridge/service/NotificationService.java
  src/main/java/com/challenger/fridge/service/SignService.java
  src/main/java/com/challenger/fridge/service/StorageService.java
  src/main/resources/application.yml
  src/test/java/com/challenger/fridge/service/NotificationServiceTest.java
  src/test/java/com/challenger/fridge/service/SignServiceTest.java
Labels: enhancement

#110 Refactor: 로그인 시 deviceToken 필수여부 옵션 추가
  src/main/java/com/challenger/fridge/controller/SignController.java
Labels: bug

#112 RefreshToken 만료시간 재설정 및 리펙토링
  src/main/java/com/challenger/fridge/security/JwtTokenProvider.java
Labels: bug

#113 회원 정보 조회 API 수정
  src/main/java/com/challenger/fridge/dto/member/MemberInfoResponse.java
  src/main/java/com/challenger/fridge/repository/MemberRepository.java
  src/main/java/com/challenger/fridge/service/MemberService.java
  src/test/java/com/challenger/fridge/service/MemberServiceTest.java
Labels: bug, enhancement

#114 회원 정보 조회 API 변경
  src/main/java/com/challenger/fridge/dto/member/MemberInfoResponse.java
  src/main/java/com/challenger/fridge/repository/MemberRepository.java
  src/main/java/com/challenger/fridge/security/JwtTokenProvider.java
  src/main/java/com/challenger/fridge/service/MemberService.java
  src/test/java/com/challenger/fridge/service/MemberServiceTest.java
Labels: bug, enhancement

#115 Test: 테스트별 로그인 변수 설정
  src/test/java/com/challenger/fridge/service/CartStorageServiceTest.java
  src/test/java/com/challenger/fridge/service/NotificationServiceTest.java
  src/test/java/com/challenger/fridge/service/SignServiceTest.java
Labels: bug

#116 테스트 리펙토링
  src/test/java/com/challenger/fridge/service/CartStorageServiceTest.java
  src/test/java/com/challenger/fridge/service/NotificationServiceTest.java
  src/test/java/com/challenger/fridge/service/SignServiceTest.java
Labels: bug

#117 Refactor: 역질렬화 오류로 인해 CartItemMoveRequest 빈 생성자 추가
  src/main/java/com/challenger/fridge/dto/cart/CartItemMoveRequest.java
Labels: bug

#118 Feature: 로그인 및 인증, 인가 예외 적용과 AccessToken 재발급 로직 수정
  src/main/java/com/challenger/fridge/handler/ExceptionResponseHandler.java
  src/main/java/com/challenger/fridge/security/JwtAccessDeniedHandler.java
  src/main/java/com/challenger/fridge/security/JwtAuthenticationFilter.java
  src/main/java/com/challenger/fridge/security/SecurityConfig.java
Labels: bug, enhancement
