Repository fridge-manager-project/backend, pull requests merged in 2024-02, with the labels that each got.

#24 Feature storage box add
  src/main/java/com/challenger/fridge/controller/StorageBoxController.java
  src/main/java/com/challenger/fridge/controller/StorageController.java
  src/main/java/com/challenger/fridge/domain/Storage.java
  src/main/java/com/challenger/fridge/domain/StorageItem.java
  src/main/java/com/challenger/fridge/domain/box/StorageBox.java
  src/main/java/com/challenger/fridge/dto/box/request/StorageBoxSaveRequest.java
  src/main/java/com/challenger/fridge/dto/box/request/StorageMethod.java
  src/main/java/com/challenger/fridge/dto/item/StorageItemDto.java
  src/main/java/com/challenger/fridge/dto/storage/request/StorageSaveRequest.java
  src/main/java/com/challenger/fridge/dto/storage/response/CategoryStorageItemResponse.java
  src/main/java/com/challenger/fridge/dto/storage/response/StorageItemDetailsResponse.java
  src/main/java/com/challenger/fridge/dto/storage/response/StorageItemResponse.java
  src/main/java/com/challenger/fridge/exception/StorageBoxNameDuplicateException.java
  src/main/java/com/challenger/fridge/exception/StorageBoxNotFoundException.java
  src/main/java/com/challenger/fridge/exception/StorageMethodMatchingException.java
  src/main/java/com/challenger/fridge/exception/StorageNameDuplicateException.java
  src/main/java/com/challenger/fridge/exception/UserEmailNotFoundException.java
  src/main/java/com/challenger/fridge/handler/ExceptionResponseHandler.java
  src/main/java/com/challenger/fridge/repository/StorageBoxRepository.java
  src/main/java/com/challenger/fridge/repository/StorageItemRepository.java
  src/main/java/com/challenger/fridge/service/StorageBoxService.java
  src/main/java/com/challenger/fridge/service/StorageService.java
  src/test/java/com/challenger/fridge/service/StorageServiceTest.java
Labels: enhancement

#28 JWT 재발급 구현 및 redis 설정 추가
  build.gradle
  src/main/java/com/challenger/fridge/config/RedisConfig.java
  src/main/java/com/challenger/fridge/config/RedisService.java
  src/main/java/com/challenger/fridge/controller/SignController.java
  src/main/java/com/challenger/fridge/domain/Category.java
  src/main/java/com/challenger/fridge/security/JwtAuthenticationFilter.java
  src/main/java/com/challenger/fridge/security/JwtTokenProvider.java
  src/main/java/com/challenger/fridge/service/SignService.java
  src/main/resources/application.yml
  src/test/java/com/challenger/fridge/redis/RedisContainerTest.java
  src/test/java/com/challenger/fridge/repository/MemberRepositoryTest.java
  src/test/java/com/challenger/fridge/service/SignServiceTest.java
Labels: enhancement

#33 Feat: refreshToken Cookie 설정 변경
  src/main/java/com/challenger/fridge/controller/SignController.java
Labels: bug

#35 Chore: Cors 설정 추가
  src/main/java/com/challenger/fridge/security/SecurityConfig.java
Labels: bug

#36 Chore: Cors 설정 추가
  src/main/java/com/challenger/fridge/security/SecurityConfig.java
Labels: bug

#41 Feat: 토큰이 없을 때 필터 로직 및 예외 구현
  src/main/java/com/challenger/fridge/controller/HomeController.java
  src/main/java/com/challenger/fridge/exception/TokenNotFoundException.java
  src/main/java/com/challenger/fridge/handler/ExceptionResponseHandler.java
  src/main/java/com/challenger/fridge/security/JwtAuthenticationFilter.java
Labels: enhancement

#42 Feat: 토큰이 없을 때 필터 로직 및 예외 구현
  src/main/java/com/challenger/fridge/controller/HomeController.java
  src/main/java/com/challenger/fridge/exception/TokenNotFoundException.java
  src/main/java/com/challenger/fridge/handler/ExceptionResponseHandler.java
  src/main/java/com/challenger/fridge/security/JwtAuthenticationFilter.java
Labels: enhancement

#46 Chore: 포트 번호 복구
  src/main/resources/application.yml
Labels: bug

#47 Chore: 포트 번호 복구
  src/main/resources/application.yml
Labels: bug

#48 Feat: 로그인 시 쿠키 설정 변경
  src/main/java/com/challenger/fridge/controller/SignController.java
  src/main/java/com/challenger/fridge/security/JwtAuthenticationFilter.java
Labels: bug

#49 Feat: 로그인 시 쿠키 설정 변경
  src/main/java/com/challenger/fridge/controller/SignController.java
  src/main/java/com/challenger/fridge/security/JwtAuthenticationFilter.java
Labels: bug

#50 Chore : 스웨거 https 설정 및 정적 자원설정
  src/main/java/com/challenger/fridge/FridgeApplication.java
  src/main/java/com/challenger/fridge/security/SecurityConfig.java
Labels: bug, enhancement

#52 Feature storage update
  src/main/java/com/challenger/fridge/controller/StorageBoxController.java
  src/main/java/com/challenger/fridge/controller/StorageController.java
  src/main/java/com/challenger/fridge/domain/StorageItem.java
  src/main/java/com/challenger/fridge/domain/box/StorageBox.java
  src/main/java/com/challenger/fridge/dto/box/request/StorageBoxUpdateRequest.java
  src/main/java/com/challenger/fridge/dto/box/response/StorageBoxResponse.java
  src/main/java/com/challenger/fridge/dto/item/request/StorageItemUpdateRequest.java
  src/main/java/com/challenger/fridge/service/StorageBoxService.java
  src/main/java/com/challenger/fridge/service/StorageService.java
  src/test/java/com/challenger/fridge/repository/StorageRepositoryTest.java
Labels: enhancement

#53 Feat: Https 설정 및 세부 보관소 api
  src/main/java/com/challenger/fridge/FridgeApplication.java
  src/main/java/com/challenger/fridge/controller/StorageBoxController.java
  src/main/java/com/challenger/fridge/controller/StorageController.java
  src/main/java/com/challenger/fridge/domain/StorageItem.java
  src/main/java/com/challenger/fridge/domain/box/StorageBox.java
  src/main/java/com/challenger/fridge/dto/box/request/StorageBoxUpdateRequest.java
  src/main/java/com/challenger/fridge/dto/box/response/StorageBoxResponse.java
  src/main/java/com/challenger/fridge/dto/item/request/StorageItemUpdateRequest.java
  src/main/java/com/challenger/fridge/security/SecurityConfig.java
  src/main/java/com/challenger/fridge/service/StorageBoxService.java
  src/main/java/com/challenger/fridge/service/StorageService.java
  src/test/java/com/challenger/fridge/repository/StorageRepositoryTest.java
Labels: bug, enhancement

#55 Chore: Cors 설정 추가
  src/main/java/com/challenger/fridge/security/SecurityConfig.java
Labels: bug, enhancement

#56 Chore: Cors 설정 추가
  src/main/java/com/challenger/fridge/security/SecurityConfig.java
Labels: bug, enhancement

#59 Feature : 장바구니에 상품 추가 및 장바구니 조회 로직
  src/main/java/com/challenger/fridge/controller/CartController.java
  src/main/java/com/challenger/fridge/controller/SignController.java
  src/main/java/com/challenger/fridge/domain/Cart.java
  src/main/java/com/challenger/fridge/domain/CartItem.java
  src/main/java/com/challenger/fridge/domain/Member.java
  src/main/java/com/challenger/fridge/dto/cart/CartItemsResponse.java
  src/main/java/com/challenger/fridge/dto/cart/CartResponse.java
  src/main/java/com/challenger/fridge/repository/CartItemRepository.java
  src/main/java/com/challenger/fridge/repository/CartRepository.java
  src/main/java/com/challenger/fridge/repository/MemberRepository.java
  src/main/java/com/challenger/fridge/service/CartService.java
  src/main/java/com/challenger/fridge/service/SignService.java
  src/test/java/com/challenger/fridge/repository/CartRepositoryTest.java
  src/test/java/com/challenger/fridge/service/CartServiceTest.java
  src/test/java/com/challenger/fridge/service/SignServiceTest.java
Labels: enhancement

#63 Feature: 장바구니 조회 및 장바구니 상품 추가 기능 구현
  src/main/java/com/challenger/fridge/controller/CartController.java
  src/main/java/com/challenger/fridge/controller/SignController.java
  src/main/java/com/challenger/fridge/domain/Cart.java
  src/main/java/com/challenger/fridge/domain/CartItem.java
  src/main/java/com/challenger/fridge/domain/Member.java
  src/main/java/com/challenger/fridge/dto/cart/CartItemsResponse.java
  src/main/java/com/challenger/fridge/dto/cart/CartResponse.java
  src/main/java/com/challenger/fridge/repository/CartItemRepository.java
  src/main/java/com/challenger/fridge/repository/CartRepository.java
  src/main/java/com/challenger/fridge/repository/MemberRepository.java
  src/main/java/com/challenger/fridge/service/CartService.java
  src/main/java/com/challenger/fridge/service/SignService.java
  src/test/java/com/challenger/fridge/repository/CartRepositoryTest.java
  src/test/java/com/challenger/fridge/service/CartServiceTest.java
  src/test/java/com/challenger/fridge/service/SignServiceTest.java
Labels: enhancement

#67 Feature: manage cart
  src/main/java/com/challenger/fridge/controller/CartController.java
  src/main/java/com/challenger/fridge/domain/Cart.java
  src/main/java/com/challenger/fridge/domain/CartItem.java
  src/main/java/com/challenger/fridge/domain/Category.java
  src/main/java/com/challenger/fridge/domain/Item.java
  src/main/java/com/challenger/fridge/domain/Member.java
  src/main/java/com/challenger/fridge/domain/MemberRefreshToken.java
  src/main/java/com/challenger/fridge/domain/Notice.java
  src/main/java/com/challenger/fridge/domain/Storage.java
  src/main/java/com/challenger/fridge/domain/StorageItem.java
  src/main/java/com/challenger/fridge/domain/box/StorageBox.java
  src/main/java/com/challenger/fridge/repository/CartItemRepository.java
  src/main/java/com/challenger/fridge/service/CartService.java
  src/main/resources/application.yml
  src/test/java/com/challenger/fridge/service/CartServiceTest.java
Labels: enhancement

#68 Feature: 장바구니 삭제 api 및 기본키 설정 변경
  src/main/java/com/challenger/fridge/controller/CartController.java
  src/main/java/com/challenger/fridge/domain/Cart.java
  src/main/java/com/challenger/fridge/domain/CartItem.java
  src/main/java/com/challenger/fridge/domain/Category.java
  src/main/java/com/challenger/fridge/domain/Item.java
  src/main/java/com/challenger/fridge/domain/Member.java
  src/main/java/com/challenger/fridge/domain/MemberRefreshToken.java
  src/main/java/com/challenger/fridge/domain/Notice.java
  src/main/java/com/challenger/fridge/domain/Storage.java
  src/main/java/com/challenger/fridge/domain/StorageItem.java
  src/main/java/com/challenger/fridge/domain/box/StorageBox.java
  src/main/java/com/challenger/fridge/repository/CartItemRepository.java
  src/main/java/com/challenger/fridge/service/CartService.java
  src/main/resources/application.yml
  src/test/java/com/challenger/fridge/service/CartServiceTest.java
Labels: enhancement

#69 Chore: ddl-auto none 설정
  src/main/resources/application.yml
Labels: invalid

#70 Chore: ddl-auto none 설정
  src/main/resources/application.yml
Labels: invalid

#71 장바구니 상품 보관소 이동 기능 구현 및 테스트 수정
  src/main/java/com/challenger/fridge/controller/CartController.java
  src/main/java/com/challenger/fridge/domain/Member.java
  src/main/java/com/challenger/fridge/domain/StorageItem.java
  src/main/java/com/challenger/fridge/dto/box/request/StorageBoxSaveRequest.java
  src/main/java/com/challenger/fridge/dto/cart/CartItemMoveRequest.java
  src/main/java/com/challenger/fridge/dto/cart/CartItemRequest.java
  src/main/java/com/challenger/fridge/dto/storage/request/StorageSaveRequest.java
  src/main/java/com/challenger/fridge/repository/CartItemRepository.java
  src/main/java/com/challenger/fridge/service/CartStorageService.java
  src/test/java/com/challenger/fridge/repository/CartRepositoryTest.java
  src/test/java/com/challenger/fridge/service/CartStorageServiceTest.java
  src/test/java/com/challenger/fridge/service/SignServiceTest.java
Labels: bug

#73 장바구니 상품 보관소 이동 기능 구현 및 테스트 수정
  src/main/java/com/challenger/fridge/controller/CartController.java
  src/main/java/com/challenger/fridge/domain/Member.java
  src/main/java/com/challenger/fridge/domain/StorageItem.java
  src/main/java/com/challenger/fridge/dto/box/request/StorageBoxSaveRequest.java
  src/main/java/com/challenger/fridge/dto/cart/CartItemMoveRequest.java
  src/main/java/com/challenger/fridge/dto/cart/CartItemRequest.java
  src/main/java/com/challenger/fridge/dto/storage/request/StorageSaveRequest.java
  src/main/java/com/challenger/fridge/repository/CartItemRepository.java
  src/main/java/com/challenger/fridge/service/CartStorageService.java
  src/test/java/com/challenger/fridge/repository/CartRepositoryTest.java
  src/test/java/com/challenger/fridge/service/CartStorageServiceTest.java
  src/test/java/com/challenger/fridge/service/SignServiceTest.java
Labels: bug, enhancement

#74 Feature storage reversion
  src/main/java/com/challenger/fridge/controller/StorageController.java
  src/main/java/com/challenger/fridge/domain/Member.java
  src/main/java/com/challenger/fridge/domain/Storage.java
  src/main/java/com/challenger/fridge/domain/box/StorageBox.java
  src/main/java/com/challenger/fridge/dto/box/request/StorageBoxSaveRequest.java
  src/main/java/com/challenger/fridge/dto/sign/SignUpRequest.java
  src/main/java/com/challenger/fridge/dto/storage/request/StorageUpdateRequest.java
  src/main/java/com/challenger/fridge/exception/CannotDeleteException.java
  src/main/java/com/challenger/fridge/handler/ExceptionResponseHandler.java
  src/main/java/com/challenger/fridge/repository/StorageRepository.java
  src/main/java/com/challenger/fridge/service/StorageService.java
Labels: bug, enhancement

#77 회원 정보 조회 및 수정 api
  src/main/java/com/challenger/fridge/controller/MemberController.java
  src/main/java/com/challenger/fridge/domain/Member.java
  src/main/java/com/challenger/fridge/domain/Storage.java
  src/main/java/com/challenger/fridge/dto/MemberInfoDto.java
  src/main/java/com/challenger/fridge/dto/box/response/StorageBoxNameResponse.java
  src/main/java/com/challenger/fridge/dto/member/MemberInfoRequest.java
  src/main/java/com/challenger/fridge/dto/member/MemberInfoResponse.java
  src/main/java/com/challenger/fridge/repository/MemberRepository.java
  src/main/java/com/challenger/fridge/service/MemberService.java
  src/test/java/com/challenger/fridge/service/MemberServiceTest.java
Labels: enhancement

#78 회원 정보 조회 및 수정 api
  src/main/java/com/challenger/fridge/controller/MemberController.java
  src/main/java/com/challenger/fridge/domain/Member.java
  src/main/java/com/challenger/fridge/domain/Storage.java
  src/main/java/com/challenger/fridge/dto/MemberInfoDto.java
  src/main/java/com/challenger/fridge/dto/box/response/StorageBoxNameResponse.java
  src/main/java/com/challenger/fridge/dto/member/MemberInfoRequest.java
  src/main/java/com/challenger/fridge/dto/member/MemberInfoResponse.java
  src/main/java/com/challenger/fridge/repository/MemberRepository.java
  src/main/java/com/challenger/fridge/service/MemberService.java
  src/test/java/com/challenger/fridge/service/MemberServiceTest.java
Labels: enhancement

#80 Feature storage reversion2
  src/main/java/com/challenger/fridge/domain/StorageItem.java
  src/main/java/com/challenger/fridge/dto/box/request/StorageBoxSaveRequest.java
  src/main/java/com/challenger/fridge/dto/item/request/StorageItemRequest.java
  src/main/java/com/challenger/fridge/dto/item/request/StorageItemUpdateRequest.java
  src/main/java/com/challenger/fridge/dto/item/response/StorageItemResponse.java
  src/main/java/com/challenger/fridge/service/StorageService.java
Labels: bug
